#################################################
# Pontificia Universidad Javeriana
# Archivo de ejecución automatica de los archivos
#################################################

GCC = gcc
PROGRAMAS = lab01 lab02 lab03

lab01:
	$(GCC) $@.c -o $@

lab02:
	$(GCC) $@.c -o $@

lab03:
	$(GCC) $@.c -o $@

clean:
	$(RM) $(PROGRAMAS)
