###################################################################################
#		Pontificia Universidad Javeriana
#	Autor: Juan José Ballesteros
#	Materia: Sistemas Operativos
#	Fichero: Automatizacion de compilación
###############################################################################

GCC = gcc
FLAGS = -lm -fopenmp

PROGRAMAS = labOMP01 labOMP02 labOMP03 labOMP04 labOMP05 labOMP06

labOMP01:
	$(GCC) $@.c -o $@ $(FLAGS)

labOMP02:
	$(GCC) $@.c -o $@ $(FLAGS)

labOMP03:
	$(GCC) $@.c -o $@ $(FLAGS)

labOMP04:
	$(GCC) $@.c -O $@ $(FLAGS)

labOMP05:
	$(GCC) $@.c -o $@ $(FLAGS)

labOMP06:
	$(GCC) $@.c -o $@ $(FLAGS)

clean:
	$(RM) $(PROGRAMAS)
