GCC = gcc

PROGRAMAS = lab01_Ballesteros lab02_Ballesteros lab03_Ballesteros


lab01_Ballesteros:
	$(GCC) $@.c -o $@

lab02_Ballesteros:
	$(GCC) $@.c -o $@

lab03_Ballesteros:
	$(GCC) $@.c -o $@

clean:
	$(RM) $(PROGRAMAS)
